import Head from 'next/head'
import Layout from '../components/layout'
import { Container, Row, Text, Spacer, Divider, Col } from '@nextui-org/react';

import type { NextPage } from 'next';


const Home: NextPage = () => {

  return (
    <Layout>
      <div >
        <Head>
          <title>Test Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main>
          <Container fluid>
            <Row justify="center">
              <Text h1>
                Main Page
              </Text>
            </Row>
            <Spacer />
            <Row justify="center">
              <Col xs={6}>
                <Text>
                  This is the frontend for the 4th weekend exercise from Encode.Club Solidity Bootcamp. 
                  This page has the functionality to display a NFT Collection, as well as a NFT Marketplace.
                </Text>
              </Col>
            </Row>
            <Divider />

            <Row><Text h3>Prerequisites</Text></Row>
            <Row><Text>User needs to have a collection </Text></Row>
          </Container>
        </main>
      </div>
    </Layout>
  )
}


export default Home;