import Head from 'next/head'
import Layout from '../components/layout'
import { Container, Row, Text, Spacer, Divider, Col, Grid } from '@nextui-org/react';

import type { NextPage } from 'next';

import RegisterBuyer from '../components/buttons/registerBuyer';
import RegisterProducer from '../components/buttons/registerProducer';

const Home: NextPage = () => {

  return (
    <Layout>
      <div >
        <Head>
          <title>Test Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main>
          <Container fluid md gap={3}>

            <Spacer />

            <Row justify="center">

              <Text h1>
                Main Page
              </Text>
            </Row>

            <Spacer />
            <Divider />
            <Spacer />

            <Grid.Container gap={2} justify="center">
              <Grid xs={6}>
                <Row justify="center">
                  <RegisterBuyer />
                </Row>
              </Grid>

              <Grid xs={6}>
                <Row justify="center">
                  <RegisterProducer />
                </Row>
              </Grid>
            </Grid.Container>

            <Spacer />
            <Divider />

          </Container>
        </main>
      </div>
    </Layout>
  )
}


export default Home;