import Head from 'next/head'
import Layout from '../components/layout'
import { Container, Row, Text, Spacer, Divider, Col, Button } from '@nextui-org/react';

import type { NextPage } from 'next';

const Home: NextPage = () => {

  return (
    <Layout>
      <div >
        <Head>
          <title>Test Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main>
          <Container fluid responsive gap={3}>
            <Spacer />
            <Row justify="center">

              <Text h1>
                Main Page
              </Text>
            </Row>
            <Spacer />
            <Spacer />
            <Spacer />
            <Row gap={3}>
              <Col>
                <Text h3>
                  Register as Buyer
                </Text>
                <Spacer />
                <Button>
                  Register
                </Button>
              </Col>
              <Col>
                <Text h3>
                  Register as Seller
                </Text>
                <Spacer />
                <Button>
                  Register
                </Button>
              </Col>
            </Row>
          </Container>
        </main>
      </div>
    </Layout>
  )
}


export default Home;